2021-02-13 15:28:07,927:__main__:INFO:Token file exists and created today
2021-02-13 15:28:07,927:__main__:INFO:Initializing session with token..
2021-02-13 15:28:07,927:__main__:INFO:Calculating everything before executing orders..
2021-02-13 15:28:07,927:__main__:INFO:Calculating weekly and monthly expiry dates..
2021-02-13 15:28:07,927:__main__:INFO:weekly expiry is : 18Feb2021, monthly expiry is: 25Feb2021
2021-02-13 15:28:09,654:__main__:INFO:StrikePrice computed as : 15150
2021-02-13 15:28:09,654:__main__:INFO:Input of get_eID fn : NIFTY, ce,18Feb2021,15150
2021-02-13 15:28:09,654:__main__:INFO:Today is not Thursday. Hence straddle
2021-02-13 15:28:11,403:__main__:INFO:Exchange Instrument ID : 47746, {'oty': ['CE'], 'ss': ['47746'], 'nn': ['NIFTY 18FEB2021 CE 15200']}
2021-02-13 15:28:11,405:__main__:INFO:Input of get_eID fn : NIFTY, pe,18Feb2021,15150
2021-02-13 15:28:11,407:__main__:INFO:Today is not Thursday. Hence straddle
2021-02-13 15:28:13,316:__main__:INFO:Exchange Instrument ID : 47743, {'oty': ['CE', 'PE'], 'ss': ['47746', '47743'], 'nn': ['NIFTY 18FEB2021 CE 15200', 'NIFTY 18FEB2021 PE 15100']}
2021-02-13 15:28:13,316:__main__:INFO:Checking margin from user..
2021-02-13 15:28:13,316:__main__:INFO:Checking balance..
2021-02-13 15:28:16,056:__main__:INFO:Balance retreived success, available cash : 1000000000
2021-02-13 15:28:16,056:__main__:INFO: 
              net_cash - 1000000000,
              strikePrice - 15150,
              Nifty Spot - 15163.3,
              BankNifty Spot - None
              exchangeInstrumentID - [47746, 47743]
              
2021-02-13 15:28:16,056:__main__:INFO:All set from prepareVars func.. Giving a go for orders..
2021-02-13 15:28:16,056:__main__:INFO:required variables set-- ready to trigger orders at desired time
2021-02-13 15:28:16,072:__main__:INFO:Required Margin Available.. Taking positions...
2021-02-13 15:28:17,068:__mp_main__:INFO:Token file exists and created today
2021-02-13 15:28:17,069:__mp_main__:INFO:Initializing session with token..
2021-02-13 15:28:17,075:__mp_main__:INFO:Placing Orders.. 

2021-02-13 15:28:17,077:__mp_main__:INFO:Token file exists and created today
2021-02-13 15:28:17,078:__mp_main__:INFO:Initializing session with token..
2021-02-13 15:28:17,083:__mp_main__:INFO:Token file exists and created today
2021-02-13 15:28:17,083:__mp_main__:INFO:Initializing session with token..
2021-02-13 15:28:17,084:__mp_main__:INFO:Placing Orders.. 

2021-02-13 15:28:17,311:__mp_main__:INFO:Token file exists and created today
2021-02-13 15:28:17,311:__mp_main__:INFO:Initializing session with token..
2021-02-13 15:28:18,722:__mp_main__:INFO: 
 Order ID for SELL 47743 is: 10037680 

2021-02-13 15:28:18,722:__mp_main__:INFO:Retreiving OrderBook..
2021-02-13 15:28:18,754:__mp_main__:INFO: 
 Order ID for SELL 47746 is: 10037681 

2021-02-13 15:28:18,754:__mp_main__:INFO:Retreiving OrderBook..
2021-02-13 15:28:20,410:__mp_main__:INFO:OrderBook result retreived success
2021-02-13 15:28:20,410:__mp_main__:INFO:
 Placed order 10037680 might be in Open or New Status, Hence retrying..0
2021-02-13 15:28:20,473:__mp_main__:INFO:OrderBook result retreived success
2021-02-13 15:28:20,473:__mp_main__:INFO:
 Placed order 10037681 might be in Open or New Status, Hence retrying..0
2021-02-13 15:28:21,423:__mp_main__:INFO:Retreiving OrderBook..
2021-02-13 15:28:21,485:__mp_main__:INFO:Retreiving OrderBook..
2021-02-13 15:28:23,067:__mp_main__:INFO:OrderBook result retreived success
2021-02-13 15:28:23,068:__mp_main__:INFO:
 Placed order 10037680 might be in Open or New Status, Hence retrying..1
2021-02-13 15:28:23,178:__mp_main__:INFO:OrderBook result retreived success
2021-02-13 15:28:23,178:__mp_main__:INFO:
 Placed order 10037681 might be in Open or New Status, Hence retrying..1
2021-02-13 15:28:24,075:__mp_main__:INFO:Retreiving OrderBook..
2021-02-13 15:28:24,185:__mp_main__:INFO:Retreiving OrderBook..
2021-02-13 15:28:25,843:__mp_main__:INFO:OrderBook result retreived success
2021-02-13 15:28:25,843:__mp_main__:INFO:
 Placed order 10037680 might be in Open or New Status, Hence retrying..2
2021-02-13 15:28:25,874:__mp_main__:INFO:OrderBook result retreived success
2021-02-13 15:28:25,874:__mp_main__:INFO:
 Placed order 10037681 might be in Open or New Status, Hence retrying..2
2021-02-13 15:28:26,882:__main__:INFO:printing new_dictR value : [{'ordrtyp': 'Entry', 'ss': '47743', 'qq': 75, 'oo': 10037680}, {'ordrtyp': 'Entry', 'ss': '47746', 'qq': 75, 'oo': 10037681}]
2021-02-13 15:28:26,991:__main__:INFO:starting multi funcs with threaded timer...
2021-02-13 15:28:27,006:__main__:INFO:--- Entering SquareOffLogic Function after placing orders ---
2021-02-13 15:28:27,006:__main__:INFO:
 Entering runSqOffLogics func,
 	 This logic runs till the end of the script and 
              checks SL/TARGET/TIMEings 

2021-02-13 15:28:27,006:__main__:INFO:Checking CurPnL for this strategy..
2021-02-13 15:28:30,420:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'tt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 469, in getPnL
    fdf['pnl']=(fdf['tt']-fdf['ltp'])*fdf['qq']
  File "C:\Users\mling\anaconda3\lib\site-packages\pandas\core\frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\mling\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'tt'
2021-02-13 15:28:30,431:__main__:INFO:Again creating a token file
2021-02-13 15:28:32,378:__main__:ERROR:Something wrong with SquareoffLogic func..
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'tt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 469, in getPnL
    fdf['pnl']=(fdf['tt']-fdf['ltp'])*fdf['qq']
  File "C:\Users\mling\anaconda3\lib\site-packages\pandas\core\frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\mling\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'tt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 638, in <module>
    runSqOffLogics()
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 567, in runSqOffLogics
    cur_PnL = getPnL()
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 480, in getPnL
    login()
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 92, in login
    logger.info(response['description'])
TypeError: string indices must be integers
2021-02-13 15:28:32,383:__main__:INFO:Strategy2 Summary: 
 Empty DataFrame
Columns: [ordrtyp, ss, nnqq, oo, tt, ltp, pnl]
Index: []
2021-02-13 15:28:32,385:__main__:INFO:Nothing to write in excel..
2021-02-13 15:28:32,387:__main__:INFO:in finally block.. Closing multi threaded func if running..
2021-02-13 15:28:32,388:__main__:INFO:-- Script Ended --
2021-02-13 15:28:32,391:__main__:INFO:-- --------------------------------------------- --
